services:
  db:
    image: postgres:15-alpine
    container_name: booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7-alpine
    container_name: booking_redis

  web:
    build: .
    container_name: booking_web
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  celery_worker:
    build: .
    container_name: booking_worker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: celery -A config worker -l info

volumes:
  postgres_data:
  static_volume:
  media_volume:
