services:
  db:
    image: postgres:15-alpine
    container_name: booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: booking_redis

  web:
    build: .
    container_name: booking_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=booking_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build: .
    container_name: booking_worker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: celery -A config worker -l info

volumes:
  postgres_data:
