# Generated by Django 6.0.1 on 2026-02-24 15:47

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(db_index=True, max_length=100)),
                ('capacity', models.IntegerField(db_index=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
