upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name yaroslav-kostenko.dev www.yaroslav-kostenko.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name yaroslav-kostenko.dev www.yaroslav-kostenko.dev;

    ssl_certificate /etc/letsencrypt/live/yaroslav-kostenko.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yaroslav-kostenko.dev/privkey.pem;

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
